
@host = http://localhost:8882/api
#@host = http://192.168.0.90/api


### LOGIN
# @name login
POST  {{host}}/auth/login
content-type: application/json

{
  "password":"samplepassword_123"
}

### ALL ITEMS
GET {{host}}/items
